---------------------------------------temp 1------------------------------------------------------------------
SELECT 0 as [NO_REFERENSI]
      ,'' as [SANDI_FORMULIR]
      ,'' as [SANDI_BANK]
      ,'1900-01-01' as [TANGGAL_DATA]
      ,'' as [BULAN_DATA]
      ,'' as [TAHUN_DATA]
      ,a.Accsts as [ID_OPERASIONAL]
      ,CRNBR as [NOMOR_AKADAWAL]
      ,ISNULL(CONVERT(date,A.AGREEDT),'1900-01-01') as [TANGGAL_AKADAKHIR]
      ,A.CRNBR as [NOMOR_AKADAKHIR]
      ,ISNULL(CONVERT(date,A.AGREEDT),'1900-01-01') as [TANGGAL_AKADAWAL]
      ,a.ACCNBR as [NOMOR_REKENING]
      ,CIFID as [ID_DEBITUR]
      ,0 as [SEQUENCEDEBITUR_ANGGOTAJOINTACCOUNT]
      ,case
	when c.SANDI in ('1','2') And convert(numeric,A.MAXCR) <=50000000 then 'UM'
	when c.SANDI in ('1','2') And convert(numeric,A.MAXCR) Between 50000001 and 500000000  then 'UK'
	when c.SANDI in ('1','2') And convert(numeric,A.MAXCR) Between 500000001 and 5000000000  then 'UT'
	else 'NU'
end as [KATEGORI_USAHADEBITUR]
      ,'' as [ID_SUMBERDANA]
      ,case
	when b.CATPORTOLBU = '60' then '51' 
	when b.CATPORTOLBU = '62' then '52' 
	else b.CATPORTOLBU
end  as [KATEGORI_PORTOFOLIO]
      ,ISNULL(CONVERT(date, A.STRTDT),'1900-01-01') as [TANGGAL_AWAL]
      ,ISNULL(CONVERT(date,A.STRTDT),'1900-01-01')  as [TANGGAL_MULAI]
      ,ISNULL(CONVERT(date,A.DUEDT),'1900-01-01')as [TANGGAL_JATUHTEMPO]
      ,'' as [SKIM_PEMBIAYAANSYARIAH]
      ,'' as [JENIS_AKAD]
      ,'' as [KARAKTERISTIK_SUMBERDANA]
      ,'' as [SIFAT_INVESTASI]
      ,'' as [METODE_BAGIHASILSUMBERDANA]
      ,0 as [PERSENTASE_NISBAH]
      ,0 as [PERSENTASE_RBHTERHADAPPBH]
      ,case
	when b.TYPECRLBU in ('P01' , '01') then '10'
	when b.TYPECRLBU in ('P02' , '02') then '20'
	when b.TYPECRLBU in ('P03' , '03') then '26'
	when b.TYPECRLBU in ('P04' , '04') then '27'
	when b.TYPECRLBU in ('P05' , '05') then '30'
	when b.TYPECRLBU in ('P06' , '06') then '45'
	when b.TYPECRLBU in ('P99')		   then '05'
	when b.TYPECRLBU in ('N01' , '01') then '80'
	when b.TYPECRLBU in ('N02' , '02') then '85'
	when b.TYPECRLBU in ('N99' )	   then '99'
	else ''
	end as [JENIS_KREDITPEMBIAYAAN]
      ,'' as [SIFAT_KREDITPEMBIAYAAN]
      ,'' as [ID_ASALTAKEOVER]
      ,a.PRODID as [JENIS_PENGGUNAAN]
      ,'' as [ORIENTASI_PENGGUNAAN]
      ,a.CCYID as [JENIS_VALUTA]
      ,B.MEASCATELBU as [KLASIFIKASI_ASETKEUANGAN]
      ,'' as [BUCKET]
      ,a.PRODID as [PROGRAM_PPEMERINTAH]
      ,a.PRODID as [SEKTOR_KREDITUSAHARAKYAT]
      ,b.ECOSECLBU as [SEKTOR_EKONOMI]
      ,b.PRJLOCLBU as [LOKASI_PENGGUNAAN]
      ,'' as [JENIS_ASET]
      ,'1900-01-01' as [WAKTU_PEROLEHANASET]
      ,'' as [JENIS_VALUTAASET]
      ,0 as [HARGA_PEROLEHANASET]
      ,0 as [JUMLAHPERIODEPENYUSUTAN_AMORTISASI]
      ,'' as [METODEPENYUSUTAN_AMORTISASI]
      ,'' as [PERIODE_PEMBAYARANSEWA]
      ,0 as [NILAISEWA_PERPERIODE]
      ,0 as [AKUMULASIPENYUSUTAN_AMORTISASI]
      ,0 as [CADANGAN_PENURUNANNILAIASERIJARAH]
      ,0 as [UANGMUKA_IJARAH]
      ,case 
    when a.TYPEINT = '0' THEN '1' 
	WHEN a.TYPEINT = '1' Then '2'
	else '0'
	end as [JENISSUKUBUNGA_IMBALAN]
      ,0 as [PERSENTASE_IMBALANKONTRAKTUAL_PDAWALKONTRAK]
      ,case
    when a.PRODID = '0615' then '5' 
	else A.INTRATE
	end as [SUKUBUNGA_PERSENTASEIMBALANKONTRAKTUAL_PDBULANLAPORAN]
      ,A.QUALRPT as [KUALITAS]
      ,CONVERT(NUMERIC,A.MAXCR) as [PLAFON_AWAL]
      ,CONVERT(NUMERIC,A.MAXCR) as [PLAFON]
      ,0 as [NILAI_KONTRAK]
      ,0 as [NILAI_PROYEK]
      ,0 as [REALISASI_PENCAIRANBULANBERJALAN]
      ,0 as [SALDO_HARGAPOKOK]
      ,0 as [Saldo_MARGINDITANGGUHKAN]
      ,CONVERT(NUMERIC,A.AMTBAL) as [BAKI_DEBET]
      ,0 as [BAKIDEBET_DLMVALUTAASAL]
      ,CONVERT(NUMERIC,A.MAXCR) - CONVERT(NUMERIC,A.AMTBAL) as [KELONGGARANTARIK_COMMITED]
      ,0 as [KELONGGARANTARIK_UNCOMMITED]
      ,CONVERT(NUMERIC,A.ACRUBLN) as [PENDAPATANBUNGA_IMBALANYGAKANDITERIMA]
      ,CONVERT(NUMERIC,A.amtbal) +  (ISNULL(CONVERT(NUMERIC,H.AMORKONV),0) *-1)  + (CONVERT(NUMERIC,A.AMORCOST)*-1) as [JUMLAH]
      ,'' as [ID_AGUNAN_JAMINAN]
      ,0 as [AGUNAN_JAMINANYGDAPATDIPERHITUNGKAN]
      ,0 as [BAGIAN_DIJAMIN]
      ,0 as [CADANGAN_KERUGIANPENURUNANNILAI]
      ,CASE
	WHEN (CASE WHEN CONVERT(NUMERIC,A.DAYPRCPASD) > CONVERT(NUMERIC,A.DAYINTPASD) THEN CONVERT(NUMERIC,A.DAYPRCPASD) ELSE CONVERT(NUMERIC,A.DAYINTPASD) END) <= 30 THEN CONVERT(NUMERIC,A.AMTCKPNIND) + CONVERT(NUMERIC,A.AMTCKPNCOLL)
	ELSE 0
END 
AS CADANGAN_KERUGIAN_PENURUNAN_NILAI_ASET_BAIK,
CASE
	WHEN (CASE WHEN CONVERT(NUMERIC,A.DAYPRCPASD) > CONVERT(NUMERIC,A.DAYINTPASD) THEN CONVERT(NUMERIC,A.DAYPRCPASD) ELSE CONVERT(NUMERIC,A.DAYINTPASD) END) BETWEEN 31 AND 90 THEN CONVERT(NUMERIC,A.AMTCKPNIND) + CONVERT(NUMERIC,A.AMTCKPNCOLL)
	ELSE 0
END 
AS CADANGAN_KERUGIAN_PENURUNAN_NILAI_ASET_KURANGBAIK,
CASE
	WHEN (CASE WHEN CONVERT(NUMERIC,A.DAYPRCPASD) > CONVERT(NUMERIC,A.DAYINTPASD) THEN CONVERT(NUMERIC,A.DAYPRCPASD) ELSE CONVERT(NUMERIC,A.DAYINTPASD) END) > 90 THEN CONVERT(NUMERIC,A.AMTCKPNIND) + CONVERT(NUMERIC,A.AMTCKPNCOLL)
	ELSE 0
END AS CADANGAN_KERUGIAN_PENURUNAN_NILAI_ASET_TIDAKBAIK
      ,0 as [FREKUENSI_PERPANJANGANKREDIT]
      ,'1900-01-01' as [TANGGAL_MACET]
      ,'' as [SEBAB_MACET]
      ,0 as [TUNGGAKAN_POKOK]
      ,0 as [TUNGGAKAN_MARGINIMBALAN]
      ,CASE
	WHEN CONVERT(NUMERIC,A.DAYPRCPASD) > CONVERT(NUMERIC,A.DAYINTPASD) THEN CONVERT(NUMERIC,A.DAYPRCPASD) 
	ELSE CONVERT(NUMERIC,A.DAYINTPASD) 
END as [JUMLAH_HARITUNGGAKAN]
      ,0 as [JUMLAH_HARITUNGGAKANPOKOK]
      ,0 as [JUMLAH_HARITUNGGAKANBAGIHASIL]
      ,0 as [DENDA]
      ,'1900-01-01' as [TANGGAL_RESTRUKTURISASIAWAL]
      ,'1900-01-01' as [TANGGAL_RESTRUKTURISASIAKHIR]
      ,'' as [CARA_REKSTRUKTURISASI]
      ,0 as [FREKUENSI_RESTRUKTURISASI]
      ,0 as [FREKUENSI_TUNGGAKAN]
      ,'' as [KONDISI_FASILITAS]
      ,'1900-01-01' as [TANGGAL_KONDISI]
      ,'' as [KODE_CABANG]
      ,'1900-01-01' as [PERIODE]
      ,'' as [STATUSRECORD]
      ,'' as [APPROVE]
      ,CONVERT(NUMERIC,A.COLVALUE) as [NilaiAgunan_YgDapatDiperhitungkan_Kredit]
      ,'' as [METODE_PENYUSUTANAMORTISASI]
      ,'' as [PERIODE_PELAPORAN]
      ,0 as [NilaiAgunan_YgDapatDiperhitungkan_KelonggaranTarik]
      ,'' as [Change]
      ,'' as [FlagStatusData]
      ,1 as [HistoryKoreksi]
from STG_MST_PRK a
left join STG_CFG_LBUSID_NEW2 b on a.ACCNBR = b.ACCNBR
left join Ref_JenisPenggunaan_Detail c on a.prodid = c.COA
left join Ref_KlasifikasiAsetKeuangan_Det d on b.MEASCATELBU = d.COA
left join Ref_KreditProgram_Detail e on a.PRODID = e.COA
left join Ref_sektorKur_detail f on a.PRODID = f.COA
left join Ref_Sektorekonomi_Detail_BI g on b.ECOSECLBU = g.COA
left join STG_MST_LOANIMPFINANCE h on a.ACCNBR = h.ACCNBR
where accsts in ('1','4')

union all

--------------------------------------temp 2---------------------------------------------------------
SELECT 0 as [NO_REFERENSI]
      ,'' as [SANDI_FORMULIR]
      ,'' as [SANDI_BANK]
      ,'1900-01-01' as [TANGGAL_DATA]
      ,'' as [BULAN_DATA]
      ,'' as [TAHUN_DATA]
      ,a.Accsts as [ID_OPERASIONAL]
      ,CRNBR as [NOMOR_AKADAWAL]
      ,ISNULL(CONVERT(date,A.AGREEDT),'1900-01-01') as [TANGGAL_AKADAKHIR]
      ,A.CRNBR as [NOMOR_AKADAKHIR]
      ,ISNULL(CONVERT(date,A.AGREEDT),'1900-01-01') as [TANGGAL_AKADAWAL]
      ,a.ACCNBR as [NOMOR_REKENING]
      ,CIFID as [ID_DEBITUR]
      ,0 as [SEQUENCEDEBITUR_ANGGOTAJOINTACCOUNT]
      ,case
	when c.sandi in ('1','2') And convert(numeric,A.MAXCR) <=50000000 then 'UM'
	when c.sandi in ('1','2') And convert(numeric,A.MAXCR) Between 50000001 and 500000000  then 'UK'
	when c.sandi in ('1','2') And convert(numeric,A.MAXCR) Between 500000001 and 5000000000  then 'UT'
	else 'NU'
end as [KATEGORI_USAHADEBITUR]
      ,'' as [ID_SUMBERDANA]
      ,case
	when b.CATPORTOLBU = '60' then '51' 
	when b.CATPORTOLBU = '62' then '52' 
	else b.CATPORTOLBU
end  as [KATEGORI_PORTOFOLIO]
      ,ISNULL(CONVERT(date, A.STRTDT),'1900-01-01') as [TANGGAL_AWAL]
      ,ISNULL(CONVERT(date,A.STRTDT),'1900-01-01')  as [TANGGAL_MULAI]
      ,ISNULL(CONVERT(date,A.DUEDT),'1900-01-01')as [TANGGAL_JATUHTEMPO]
      ,'' as [SKIM_PEMBIAYAANSYARIAH]
      ,'' as [JENIS_AKAD]
      ,'' as [KARAKTERISTIK_SUMBERDANA]
      ,'' as [SIFAT_INVESTASI]
      ,'' as [METODE_BAGIHASILSUMBERDANA]
      ,0 as [PERSENTASE_NISBAH]
      ,0 as [PERSENTASE_RBHTERHADAPPBH]
      ,case
	when b.TYPECRLBU in ('P01' , '01') then '10'
	when b.TYPECRLBU in ('P02' , '02') then '20'
	when b.TYPECRLBU in ('P03' , '03') then '26'
	when b.TYPECRLBU in ('P04' , '04') then '27'
	when b.TYPECRLBU in ('P05' , '05') then '30'
	when b.TYPECRLBU in ('P06' , '06') then '45'
	when b.TYPECRLBU in ('P99')		   then '05'
	when b.TYPECRLBU in ('N01' , '01') then '80'
	when b.TYPECRLBU in ('N02' , '02') then '85'
	when b.TYPECRLBU in ('N99' )	   then '99'
	else ''
	end as [JENIS_KREDITPEMBIAYAAN]
      ,'' as [SIFAT_KREDITPEMBIAYAAN]
      ,'' as [ID_ASALTAKEOVER]
      ,a.prodid as [JENIS_PENGGUNAAN]
      ,'' as [ORIENTASI_PENGGUNAAN]
      ,a.CCYID as [JENIS_VALUTA]
      ,B.MEASCATELBU as [KLASIFIKASI_ASETKEUANGAN]
      ,'' as [BUCKET]
      ,a.PRODID as [PROGRAM_PPEMERINTAH]
      ,a.PRODID as [SEKTOR_KREDITUSAHARAKYAT]
      ,b.ECOSECLBU as [SEKTOR_EKONOMI]
      ,b.PRJLOCLBU as [LOKASI_PENGGUNAAN]
      ,'' as [JENIS_ASET]
      ,'1900-01-01' as [WAKTU_PEROLEHANASET]
      ,'' as [JENIS_VALUTAASET]
      ,0 as [HARGA_PEROLEHANASET]
      ,0 as [JUMLAHPERIODEPENYUSUTAN_AMORTISASI]
      ,'' as [METODEPENYUSUTAN_AMORTISASI]
      ,'' as [PERIODE_PEMBAYARANSEWA]
      ,0 as [NILAISEWA_PERPERIODE]
      ,0 as [AKUMULASIPENYUSUTAN_AMORTISASI]
      ,0 as [CADANGAN_PENURUNANNILAIASERIJARAH]
      ,0 as [UANGMUKA_IJARAH]
      ,case 
    when a.TYPEINT = '0' THEN '1' 
	WHEN a.TYPEINT = '1' Then '2'
	else '0'
	end as [JENISSUKUBUNGA_IMBALAN]
      ,0 as [PERSENTASE_IMBALANKONTRAKTUAL_PDAWALKONTRAK]
      ,case
    when a.PRODID = '0615' then '5' 
	else INTRATE
	end as [SUKUBUNGA_PERSENTASEIMBALANKONTRAKTUAL_PDBULANLAPORAN]
      ,ISNULL(H.QUALRPT,'') as [KUALITAS]
      ,CONVERT(NUMERIC,a.MAXCR) as [PLAFON_AWAL]
      ,CONVERT(NUMERIC,a.MAXCR) as [PLAFON]
      ,0 as [NILAI_KONTRAK]
      ,0 as [NILAI_PROYEK]
      ,0 as [REALISASI_PENCAIRANBULANBERJALAN]
      ,0 as [SALDO_HARGAPOKOK]
      ,0 as [Saldo_MARGINDITANGGUHKAN]
      ,ISNULL(H.AMTBAL,0) as [BAKI_DEBET]
      ,0 as [BAKIDEBET_DLMVALUTAASAL]
      ,CONVERT(NUMERIC,ISNULL(H.WDRSPARE,0)) as [KELONGGARANTARIK_COMMITED]
      ,0 as [KELONGGARANTARIK_UNCOMMITED]
      ,0 as [PENDAPATANBUNGA_IMBALANYGAKANDITERIMA]
      ,CONVERT(NUMERIC,ISNULL(H.AMTBAL,0)) - CONVERT(NUMERIC,ISNULL(H.AMORALL,0)) as [JUMLAH]
      ,'' as [ID_AGUNAN_JAMINAN]
      ,0 as [AGUNAN_JAMINANYGDAPATDIPERHITUNGKAN]
      ,0 as [BAGIAN_DIJAMIN]
      ,0 as [CADANGAN_KERUGIANPENURUNANNILAI]
      ,case 
    WHEN (CASE WHEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) > CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) THEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) ELSE CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) END) <= 30 THEN CONVERT(NUMERIC,ISNULL(H.AMTCKPNIND,0)) + CONVERT(NUMERIC,ISNULL(H.AMTCKPNCOLL,0))
	ELSE 0
     end as [CADANGAN_KERUGIANPENURUNANNILAIASET_BAIK]
      ,case 
   WHEN (CASE WHEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) > CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) THEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) ELSE CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) END) BETWEEN 31 AND 90 THEN CONVERT(NUMERIC,ISNULL(H.AMTCKPNIND,0)) + CONVERT(NUMERIC,ISNULL(H.AMTCKPNCOLL,0))
	ELSE 0
	end as [CADANGAN_KERUGIANPENURUNANNILAIASET_KURANGBAIK]
      ,case
    WHEN (CASE WHEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) > CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) THEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) ELSE CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) END) > 90 THEN CONVERT(NUMERIC,H.AMTCKPNIND) + CONVERT(NUMERIC,ISNULL(H.AMTCKPNCOLL,0))
	ELSE 0
end as [CADANGAN_KERUGIANPENURUNANNILAIASET_TIDAKBAIK]
      ,0 as [FREKUENSI_PERPANJANGANKREDIT]
      ,'1900-01-01' as [TANGGAL_MACET]
      ,'' as [SEBAB_MACET]
      ,0 as [TUNGGAKAN_POKOK]
      ,CONVERT(NUMERIC,ISNULL(H.AMTINTPASD,0)) as [TUNGGAKAN_MARGINIMBALAN]
      ,CASE
	  WHEN CONVERT(NUMERIC,H.DAYPRCPASD) > CONVERT(NUMERIC,H.DAYINTPASD) THEN CONVERT(NUMERIC,H.DAYPRCPASD) 
	ELSE CONVERT(NUMERIC,H.DAYINTPASD) 
	END as [JUMLAH_HARITUNGGAKAN]
      ,0 as [JUMLAH_HARITUNGGAKANPOKOK]
      ,0 as [JUMLAH_HARITUNGGAKANBAGIHASIL]
      ,0 as [DENDA]
      ,'1900-01-01' as [TANGGAL_RESTRUKTURISASIAWAL]
      ,'1900-01-01' as [TANGGAL_RESTRUKTURISASIAKHIR]
      ,'' as [CARA_REKSTRUKTURISASI]
      ,0 as [FREKUENSI_RESTRUKTURISASI]
      ,0 as [FREKUENSI_TUNGGAKAN]
      ,'' as [KONDISI_FASILITAS]
      ,'1900-01-01' as [TANGGAL_KONDISI]
      ,'' as [KODE_CABANG]
      ,'1900-01-01' as [PERIODE]
      ,'' as [STATUSRECORD]
      ,'' as [APPROVE]
      ,ISNULL(h.COLVALUE,0) as [NilaiAgunan_YgDapatDiperhitungkan_Kredit]
      ,'' as [METODE_PENYUSUTANAMORTISASI]
      ,'' as [PERIODE_PELAPORAN]
      ,0 as [NilaiAgunan_YgDapatDiperhitungkan_KelonggaranTarik]
      ,'' as [Change]
      ,'' as [FlagStatusData]
      ,1 as [HistoryKoreksi]
FROM Stg_MST_LOANIMP a
left join stg_cfg_lbusid_new2 b on a.ACCNBR = b.ACCNBR
left join Ref_JenisPenggunaan_Detail c on a.PRODID = C.coa
LEFT JOIN Ref_KlasifikasiAsetKeuangan_Det d on b.MEASCATELBU = d.coa
left join Ref_KreditProgram_Detail e on a.PRODID = E.coa
LEFT JOIN Ref_SektorKur_Detail f on a.PRODID = F.coa
LEFT JOIN Ref_SektorEkonomi_Detail_bi g on b.ECOSECLBU = G.coa
LEFT JOIN STG_MST_LOANIMPFINANCE h on a.ACCNBR = h.ACCNBR
where ACCSTS in('1','4','5')



union all

-------------------------------------temp 3-----------------------------------------------------------
SELECT 0 as [NO_REFERENSI]
      ,'' as [SANDI_FORMULIR]
      ,'' as [SANDI_BANK]
      ,'1900-01-01' as [TANGGAL_DATA]
      ,'' as [BULAN_DATA]
      ,'' as [TAHUN_DATA]
      ,a.Accsts as [ID_OPERASIONAL]
      ,CRNBR as [NOMOR_AKADAWAL]
      ,ISNULL(CONVERT(date,A.AGREEDT),'1900-01-01') as [TANGGAL_AKADAKHIR]
      ,A.CRNBR as [NOMOR_AKADAKHIR]
      ,ISNULL(CONVERT(date,A.AGREEDT),'1900-01-01') as [TANGGAL_AKADAWAL]
      ,a.ACCNBR as [NOMOR_REKENING]
      ,CIFID as [ID_DEBITUR]
      ,0 as [SEQUENCEDEBITUR_ANGGOTAJOINTACCOUNT]
      ,case
	when c.sandi in ('1','2') And convert(numeric,A.MAXCR) <=50000000 then 'UM'
	when c.sandi in ('1','2') And convert(numeric,A.MAXCR) Between 50000001 and 500000000  then 'UK'
	when c.sandi in ('1','2') And convert(numeric,A.MAXCR) Between 500000001 and 5000000000  then 'UT'
	else 'NU'
end as [KATEGORI_USAHADEBITUR]
      ,'' as [ID_SUMBERDANA]
      ,case
	when b.CATPORTOLBU = '60' then '51' 
	when b.CATPORTOLBU = '62' then '52' 
	else b.CATPORTOLBU
end  as [KATEGORI_PORTOFOLIO]
      ,ISNULL(CONVERT(date, A.STRTDT),'1900-01-01') as [TANGGAL_AWAL]
      ,ISNULL(CONVERT(date,A.STRTDT),'1900-01-01')  as [TANGGAL_MULAI]
      ,ISNULL(CONVERT(date,A.DUEDT),'1900-01-01')as [TANGGAL_JATUHTEMPO]
      ,'' as [SKIM_PEMBIAYAANSYARIAH]
      ,'' as [JENIS_AKAD]
      ,'' as [KARAKTERISTIK_SUMBERDANA]
      ,'' as [SIFAT_INVESTASI]
      ,'' as [METODE_BAGIHASILSUMBERDANA]
      ,0 as [PERSENTASE_NISBAH]
      ,0 as [PERSENTASE_RBHTERHADAPPBH]
      ,case
	when b.TYPECRLBU in ('P01' , '01') then '10'
	when b.TYPECRLBU in ('P02' , '02') then '20'
	when b.TYPECRLBU in ('P03' , '03') then '26'
	when b.TYPECRLBU in ('P04' , '04') then '27'
	when b.TYPECRLBU in ('P05' , '05') then '30'
	when b.TYPECRLBU in ('P06' , '06') then '45'
	when b.TYPECRLBU in ('P99')		   then '05'
	when b.TYPECRLBU in ('N01' , '01') then '80'
	when b.TYPECRLBU in ('N02' , '02') then '85'
	when b.TYPECRLBU in ('N99' )	   then '99'
	else ''
	end as [JENIS_KREDITPEMBIAYAAN]
      ,'' as [SIFAT_KREDITPEMBIAYAAN]
      ,'' as [ID_ASALTAKEOVER]
      ,A.PRODID as [JENIS_PENGGUNAAN]
      ,'' as [ORIENTASI_PENGGUNAAN]
      ,a.CCYID as [JENIS_VALUTA]
      ,B.MEASCATELBU as [KLASIFIKASI_ASETKEUANGAN]
      ,'' as [BUCKET]
      ,a.PRODID as [PROGRAM_PPEMERINTAH]
      ,a.PRODID as [SEKTOR_KREDITUSAHARAKYAT]
      ,b.ECOSECLBU as [SEKTOR_EKONOMI]
      ,b.PRJLOCLBU as [LOKASI_PENGGUNAAN]
      ,'' as [JENIS_ASET]
      ,'1900-01-01' as [WAKTU_PEROLEHANASET]
      ,'' as [JENIS_VALUTAASET]
      ,0 as [HARGA_PEROLEHANASET]
      ,0 as [JUMLAHPERIODEPENYUSUTAN_AMORTISASI]
      ,'' as [METODEPENYUSUTAN_AMORTISASI]
      ,'' as [PERIODE_PEMBAYARANSEWA]
      ,0 as [NILAISEWA_PERPERIODE]
      ,0 as [AKUMULASIPENYUSUTAN_AMORTISASI]
      ,0 as [CADANGAN_PENURUNANNILAIASERIJARAH]
      ,0 as [UANGMUKA_IJARAH]
      ,case 
    when a.TYPEINT = '0' THEN '1' 
	WHEN a.TYPEINT = '1' Then '2'
	else '0'
	end as [JENISSUKUBUNGA_IMBALAN]
      ,0 as [PERSENTASE_IMBALANKONTRAKTUAL_PDAWALKONTRAK]
      ,case
    when a.PRODID = '0615' then '5' 
	else INTRATE
	end as [SUKUBUNGA_PERSENTASEIMBALANKONTRAKTUAL_PDBULANLAPORAN]
      ,ISNULL(H.QUALRPT,'') as [KUALITAS]
      ,CONVERT(NUMERIC,a.MAXCR) as [PLAFON_AWAL]
      ,CONVERT(NUMERIC,a.MAXCR) as [PLAFON]
      ,0 as [NILAI_KONTRAK]
      ,0 as [NILAI_PROYEK]
      ,0 as [REALISASI_PENCAIRANBULANBERJALAN]
      ,0 as [SALDO_HARGAPOKOK]
      ,0 as [Saldo_MARGINDITANGGUHKAN]
      ,ISNULL(H.AMTBAL,0) as [BAKI_DEBET]
      ,0 as [BAKIDEBET_DLMVALUTAASAL]
      ,CONVERT(NUMERIC,ISNULL(H.WDRSPARE,0)) as [KELONGGARANTARIK_COMMITED]
      ,0 as [KELONGGARANTARIK_UNCOMMITED]
      ,0 as [PENDAPATANBUNGA_IMBALANYGAKANDITERIMA]
      ,CONVERT(NUMERIC,ISNULL(H.AMTBAL,0)) - CONVERT(NUMERIC,ISNULL(H.AMORALL,0)) as [JUMLAH]
      ,'' as [ID_AGUNAN_JAMINAN]
      ,0 as [AGUNAN_JAMINANYGDAPATDIPERHITUNGKAN]
      ,0 as [BAGIAN_DIJAMIN]
      ,0 as [CADANGAN_KERUGIANPENURUNANNILAI]
      ,case 
    WHEN (CASE WHEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) > CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) THEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) ELSE CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) END) <= 30 THEN CONVERT(NUMERIC,ISNULL(H.AMTCKPNIND,0)) + CONVERT(NUMERIC,ISNULL(H.AMTCKPNCOLL,0))
	ELSE 0
     end as [CADANGAN_KERUGIANPENURUNANNILAIASET_BAIK]
      ,case 
   WHEN (CASE WHEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) > CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) THEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) ELSE CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) END) BETWEEN 31 AND 90 THEN CONVERT(NUMERIC,ISNULL(H.AMTCKPNIND,0)) + CONVERT(NUMERIC,ISNULL(H.AMTCKPNCOLL,0))
	ELSE 0
	end as [CADANGAN_KERUGIANPENURUNANNILAIASET_KURANGBAIK]
      ,case
    WHEN (CASE WHEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) > CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) THEN CONVERT(NUMERIC,ISNULL(H.DAYPRCPASD,0)) ELSE CONVERT(NUMERIC,ISNULL(H.DAYINTPASD,0)) END) > 90 THEN CONVERT(NUMERIC,H.AMTCKPNIND) + CONVERT(NUMERIC,ISNULL(H.AMTCKPNCOLL,0))
	ELSE 0
end as [CADANGAN_KERUGIANPENURUNANNILAIASET_TIDAKBAIK]
      ,0 as [FREKUENSI_PERPANJANGANKREDIT]
      ,'1900-01-01' as [TANGGAL_MACET]
      ,'' as [SEBAB_MACET]
      ,0 as [TUNGGAKAN_POKOK]
      ,CONVERT(NUMERIC,ISNULL(H.AMTINTPASD,0)) as [TUNGGAKAN_MARGINIMBALAN]
      ,CASE 
	  WHEN CONVERT(NUMERIC,ISNULL(DAYPRCPASD,0)) > CONVERT(NUMERIC,ISNULL(DAYINTPASD,0)) THEN CONVERT(NUMERIC,ISNULL(DAYPRCPASD,0)) 
	ELSE CONVERT(NUMERIC,ISNULL(DAYINTPASD,0)) 
	END as [JUMLAH_HARITUNGGAKAN]
      ,0 as [JUMLAH_HARITUNGGAKANPOKOK]
      ,0 as [JUMLAH_HARITUNGGAKANBAGIHASIL]
      ,0 as [DENDA]
      ,'1900-01-01' as [TANGGAL_RESTRUKTURISASIAWAL]
      ,'1900-01-01' as [TANGGAL_RESTRUKTURISASIAKHIR]
      ,'' as [CARA_REKSTRUKTURISASI]
      ,0 as [FREKUENSI_RESTRUKTURISASI]
      ,0 as [FREKUENSI_TUNGGAKAN]
      ,'' as [KONDISI_FASILITAS]
      ,'1900-01-01' as [TANGGAL_KONDISI]
      ,'' as [KODE_CABANG]
      ,'1900-01-01' as [PERIODE]
      ,'' as [STATUSRECORD]
      ,'' as [APPROVE]
      ,ISNULL(h.COLVALUE,0) as [NilaiAgunan_YgDapatDiperhitungkan_Kredit]
      ,'' as [METODE_PENYUSUTANAMORTISASI]
      ,'' as [PERIODE_PELAPORAN]
      ,0 as [NilaiAgunan_YgDapatDiperhitungkan_KelonggaranTarik]
      ,'' as [Change]
      ,'' as [FlagStatusData]
      ,1 as [HistoryKoreksi]
FROM Stg_MST_LOAN a
left join stg_cfg_lbusid_new2 b on a.ACCNBR = b.ACCNBR
left join Ref_JenisPenggunaan_Detail c on a.PRODID = C.coa
LEFT JOIN Ref_KlasifikasiAsetKeuangan_Det d on b.MEASCATELBU = d.coa
left join Ref_KreditProgram_Detail e on a.PRODID = E.coa
LEFT JOIN Ref_SektorKur_Detail f on a.PRODID = F.coa
LEFT JOIN Ref_SektorEkonomi_Detail_bi g on b.ECOSECLBU = G.coa
LEFT JOIN STG_MST_LOANIMPFINANCE h on a.ACCNBR = h.ACCNBR
where ACCSTS in('1')